# Generated by Django 4.2.7 on 2025-09-28 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metric_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "actual_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("period", models.CharField(max_length=50)),
                ("period_start_date", models.DateField(blank=True, null=True)),
                ("period_end_date", models.DateField(blank=True, null=True)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("count", "Count"),
                            ("sum", "Sum"),
                            ("average", "Average"),
                            ("percentage", "Percentage"),
                            ("currency", "Currency"),
                        ],
                        default="count",
                        max_length=20,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "Custom Metric",
                "verbose_name_plural": "Custom Metrics",
                "ordering": ["template", "period", "metric_name"],
            },
        ),
        migrations.CreateModel(
            name="DashboardTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "csv_template",
                    models.FileField(
                        blank=True, null=True, upload_to="dashboard_templates/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("custom", "Custom"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Template",
                "verbose_name_plural": "Dashboard Templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MetricDataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("date_recorded", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_points",
                        to="analytics.custommetric",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metric Data Point",
                "verbose_name_plural": "Metric Data Points",
                "ordering": ["-date_recorded"],
            },
        ),
        migrations.CreateModel(
            name="DashboardView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("configuration", models.JSONField(default=dict)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("line", "Line Chart"),
                            ("bar", "Bar Chart"),
                            ("pie", "Pie Chart"),
                            ("area", "Area Chart"),
                            ("scatter", "Scatter Plot"),
                            ("table", "Table"),
                        ],
                        default="line",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="analytics.dashboardtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard View",
                "verbose_name_plural": "Dashboard Views",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="custommetric",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metrics",
                to="analytics.dashboardtemplate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="custommetric",
            unique_together={("template", "metric_name", "period")},
        ),
    ]
