# Generated by Django 4.2.7 on 2025-09-29 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analytics", "0002_custommetric_dashboardtemplate_metricdatapoint_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Base",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="📊", max_length=50)),
                ("color", models.CharField(default="blue", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Base",
                "verbose_name_plural": "Bases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="📋", max_length=50)),
                ("color", models.CharField(default="gray", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_view",
                    models.CharField(
                        choices=[
                            ("grid", "Grid View"),
                            ("calendar", "Calendar View"),
                            ("kanban", "Kanban View"),
                            ("gallery", "Gallery View"),
                        ],
                        default="grid",
                        max_length=20,
                    ),
                ),
                (
                    "base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="analytics.base",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table",
                "verbose_name_plural": "Tables",
                "ordering": ["base", "name"],
                "unique_together": {("base", "name")},
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField(default=dict)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="analytics.table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Record",
                "verbose_name_plural": "Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TableField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("single_line_text", "Single Line Text"),
                            ("long_text", "Long Text"),
                            ("number", "Number"),
                            ("phone_number", "Phone Number"),
                            ("email", "Email"),
                            ("url", "URL"),
                            ("date", "Date"),
                            ("checkbox", "Checkbox"),
                            ("select", "Select"),
                            ("multi_select", "Multi Select"),
                            ("rating", "Rating"),
                            ("currency", "Currency"),
                            ("percentage", "Percentage"),
                            ("duration", "Duration"),
                        ],
                        default="single_line_text",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_required", models.BooleanField(default=False)),
                ("is_primary", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("options", models.JSONField(blank=True, default=dict)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="analytics.table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table Field",
                "verbose_name_plural": "Table Fields",
                "ordering": ["table", "order", "name"],
                "unique_together": {("table", "name")},
            },
        ),
    ]
