# Generated by Django 4.2 on 2026-01-20 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="founded_year",
            field=models.IntegerField(
                blank=True, help_text="Year the company was founded", null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="logo_url",
            field=models.URLField(
                blank=True,
                help_text="URL to company logo",
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="size_category",
            field=models.CharField(
                blank=True,
                help_text="Size category (e.g., '10000+', 'Self-employed')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="specialties",
            field=models.TextField(
                blank=True, help_text="Company specialties or focus areas"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="bio",
            field=models.TextField(blank=True, help_text="Biography or about section"),
        ),
        migrations.AddField(
            model_name="contact",
            name="birthday",
            field=models.DateField(blank=True, help_text="Date of birth", null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="headline",
            field=models.CharField(
                blank=True, help_text="Professional headline or tagline", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="pronouns",
            field=models.CharField(
                blank=True, help_text="Preferred pronouns", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="skills",
            field=models.TextField(blank=True, help_text="Skills or competencies"),
        ),
    ]
