# Generated by Django 4.2 on 2026-01-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_company_founded_year_company_logo_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="latest_post",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time of latest social media post",
                null=True,
            ),
        ),
    ]
