# Generated by Django 4.2 on 2026-01-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_contact_latest_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="company",
            name="postal_code",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="contact",
            name="headline",
            field=models.CharField(
                blank=True, help_text="Professional headline or tagline", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="mobile",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="contact",
            name="postal_code",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="contact",
            name="pronouns",
            field=models.CharField(
                blank=True, help_text="Preferred pronouns", max_length=50
            ),
        ),
    ]
