# Generated by Django 4.2 on 2026-01-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_alter_company_phone_alter_company_postal_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="postal_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="job_title",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="contact",
            name="postal_code",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
