# Generated by Django 4.2 on 2026-01-20 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_alter_contact_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="linkedin_url",
            field=models.URLField(
                blank=True,
                help_text="LinkedIn company page URL",
                validators=[django.core.validators.URLValidator()],
            ),
        ),
    ]
