# Generated by Django 4.2.7 on 2026-01-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_sequence_contact_last_contact_sequencestep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("call", "Phone Call"),
                    ("email", "Email"),
                    ("meeting", "Meeting"),
                    ("task", "Task"),
                    ("note", "Note"),
                    ("demo", "Demo"),
                    ("proposal", "Proposal"),
                    ("linkedin", "LinkedIn"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sequencestep",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("call", "Phone Call"),
                    ("email", "Email"),
                    ("meeting", "Meeting"),
                    ("task", "Task"),
                    ("note", "Note"),
                    ("demo", "Demo"),
                    ("proposal", "Proposal"),
                    ("linkedin", "LinkedIn"),
                ],
                default="email",
                max_length=20,
            ),
        ),
    ]
