# Generated by Django 4.2.7 on 2026-01-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_activitythread_activity_thread"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
