# Generated by Django 4.2.7 on 2026-01-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0011_alter_activity_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Link to the message (LinkedIn, email thread, etc.)",
            ),
        ),
    ]
