# Generated by Django 4.2.7 on 2026-01-21 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "0012_activity_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="call_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_answer", "No answer"),
                    ("left_voicemail", "Left voicemail"),
                    ("connected_interested", "Connected - interested"),
                    ("connected_not_interested", "Connected - not interested"),
                    ("wrong_number", "Wrong number"),
                    ("scheduled_followup", "Scheduled follow-up"),
                    ("other", "Other"),
                ],
                help_text="Structured outcome for call activities",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="clicks_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times links in an email activity were clicked",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="delivery_status",
            field=models.CharField(
                blank=True,
                help_text="Delivery status for email activities (e.g. queued, sent, bounced)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="direction",
            field=models.CharField(
                choices=[
                    ("inbound", "Inbound"),
                    ("outbound", "Outbound"),
                    ("system", "System"),
                ],
                default="outbound",
                help_text="Direction of the activity (inbound, outbound, or system-generated)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Duration of the call in seconds (for call activities)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="end_at",
            field=models.DateTimeField(
                blank=True, help_text="End time for meeting-type activities", null=True
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="external_message_id",
            field=models.CharField(
                blank=True,
                help_text="Identifier from the external email provider, if applicable",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="is_pinned",
            field=models.BooleanField(
                default=False,
                help_text="Pinned activities are shown at the top of timelines",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="last_clicked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="last_opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="location_url",
            field=models.URLField(
                blank=True,
                help_text="Meeting location or conferencing link (e.g. Zoom, Google Meet)",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="meeting_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("discovery", "Discovery"),
                    ("demo", "Demo"),
                    ("renewal", "Renewal"),
                    ("qbr", "QBR"),
                    ("other", "Other"),
                ],
                help_text="Categorization for meeting-type activities",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="opens_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times an email activity was opened"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="phone_number_used",
            field=models.CharField(
                blank=True,
                help_text="Phone number used for the call (dialer/rep number)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="recording_url",
            field=models.URLField(
                blank=True, help_text="URL to call recording, if available"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="sequence_step",
            field=models.ForeignKey(
                blank=True,
                help_text="Sequence step that generated this activity, if any",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_activities",
                to="crm.sequencestep",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="start_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Start time for meeting-type activities, if different from due date",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="task_priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                help_text="Priority for task-type activities",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="task_type",
            field=models.CharField(
                blank=True,
                help_text='Optional fine-grained task type, e.g. "LINKEDIN_VIEW_PROFILE", "FOLLOWUP", "MEETING_PREP"',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="transcript",
            field=models.TextField(
                blank=True,
                help_text="Optional transcript or notes from the call recording",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="can_call",
            field=models.BooleanField(
                default=True, help_text="Allow phone calls to this contact"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="can_email_outbound",
            field=models.BooleanField(
                default=True,
                help_text="Allow one-to-one and sequence emails to this contact",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="can_linkedin",
            field=models.BooleanField(
                default=True,
                help_text="Allow LinkedIn and social outreach to this contact",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="can_marketing_email",
            field=models.BooleanField(
                default=True, help_text="Allow bulk/marketing emails to this contact"
            ),
        ),
        migrations.AddField(
            model_name="sequence",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("archived", "Archived"),
                ],
                default="active",
                help_text="Lifecycle status of this sequence",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sequencestep",
            name="auto_execute",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, the step will execute automatically (e.g. send email). If disabled, a task will be created for a human to complete.",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("call", "Phone Call"),
                    ("email", "Email"),
                    ("meeting", "Meeting"),
                    ("task", "Task"),
                    ("note", "Note"),
                    ("demo", "Demo"),
                    ("proposal", "Proposal"),
                    ("linkedin", "LinkedIn"),
                    ("system", "System"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Link to the message (email thread, LinkedIn conversation, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Legacy flag; prefer using status going forward"
            ),
        ),
        migrations.AlterField(
            model_name="sequencestep",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("call", "Phone Call"),
                    ("email", "Email"),
                    ("meeting", "Meeting"),
                    ("task", "Task"),
                    ("note", "Note"),
                    ("demo", "Demo"),
                    ("proposal", "Proposal"),
                    ("linkedin", "LinkedIn"),
                    ("system", "System"),
                ],
                default="email",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sequencestep",
            name="offset_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Days after previous step to schedule this step (0 = same day)",
            ),
        ),
        migrations.CreateModel(
            name="SequenceEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("stopped_on_reply", "Stopped on reply"),
                            ("unsubscribed", "Unsubscribed"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        help_text="Current state of this enrollment within the sequence",
                        max_length=20,
                    ),
                ),
                (
                    "current_step_index",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Zero-based index of the next step to execute",
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the next step should be executed",
                        null=True,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequence_enrollments",
                        to="crm.contact",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sequence_enrollments",
                        to="crm.deal",
                    ),
                ),
                (
                    "last_executed_step",
                    models.ForeignKey(
                        blank=True,
                        help_text="Last step that was executed for this enrollment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crm.sequencestep",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sequence_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="crm.sequence",
                    ),
                ),
            ],
            options={
                "ordering": ["-next_run_at", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="sequence_enrollment",
            field=models.ForeignKey(
                blank=True,
                help_text="Sequence enrollment associated with this activity, if any",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="crm.sequenceenrollment",
            ),
        ),
    ]
