# Generated by Django 4.2.7 on 2026-01-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0013_activity_call_outcome_activity_clicks_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="icp_fit_score",
            field=models.PositiveIntegerField(
                default=0,
                help_text="ICP fit score from 0 (poor fit) to 100 (excellent fit)",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="icp_fit_tier",
            field=models.CharField(
                blank=True,
                help_text="Simple ICP tier label derived from the fit score (e.g. A, B, C, D)",
                max_length=1,
            ),
        ),
    ]
