# Generated by Django 4.2 on 2026-01-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0014_company_icp_fit_score_company_icp_fit_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="linkedin",
            field=models.URLField(blank=True, help_text="LinkedIn profile URL"),
        ),
    ]
