# Generated by Django 4.2 on 2026-01-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0015_contact_linkedin"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="competitor",
            field=models.BooleanField(
                default=False, help_text="Mark this company as a competitor"
            ),
        ),
    ]
