# Generated by Django 4.2 on 2026-01-29 07:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0016_add_company_competitor_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="facility_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of facilities (e.g. 3–15 ideal for LTC)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="priority_tier",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Tier 1"), (2, "Tier 2"), (3, "Tier 3")],
                help_text="Priority tier 1, 2, or 3",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="outreach_status",
            field=models.CharField(
                choices=[
                    ("not_contacted", "Not contacted"),
                    ("reached_out", "Reached out"),
                    ("responded", "Responded"),
                    ("bounced", "Bounced"),
                    ("not_a_fit", "Not a fit"),
                ],
                default="not_contacted",
                help_text="Outreach stage for this contact",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PainSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            ("job_posting", "Job posting"),
                            ("glassdoor", "Glassdoor"),
                            ("news", "News mention"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("note", models.TextField(blank=True)),
                (
                    "observed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pain_signals",
                        to="crm.company",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pain_signals",
                        to="crm.contact",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pain signals",
                "ordering": ["-observed_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperatingArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("state", "State"),
                            ("province", "Province"),
                            ("region", "Region"),
                            ("country", "Country"),
                            ("other", "Other"),
                        ],
                        default="state",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="e.g. CA, Ontario, Bavaria", max_length=100
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, help_text="Optional short code", max_length=50
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operating_areas",
                        to="crm.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Operating areas",
                "ordering": ["kind", "value"],
            },
        ),
    ]
