# Generated by Django 4.2 on 2026-01-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0017_prospecting_fields_and_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="PainType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=120)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="painsignal",
            name="pain_signal",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="painsignal",
            name="signal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("job_posting", "Job posting"),
                    ("glassdoor", "Glassdoor"),
                    ("news", "News mention"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Legacy; prefer pain_types",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="painsignal",
            name="pain_types",
            field=models.ManyToManyField(
                blank=True, related_name="pain_signals", to="crm.paintype"
            ),
        ),
    ]
