# Generated by Django 4.2 on 2026-01-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0019_seed_pain_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="painsignal",
            name="pain_signal",
            field=models.TextField(blank=True),
        ),
    ]
