# Generated by Django 4.2 on 2026-01-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0020_pain_signal_textfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="verified",
            field=models.BooleanField(
                default=False,
                help_text="Contact has been verified (e.g. email/LinkedIn confirmed)",
            ),
        ),
    ]
