# Generated by Django 4.2 on 2026-01-30 04:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0021_contact_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_url",
                    models.URLField(
                        help_text="Source URL; LLM will read and populate fields below.",
                        max_length=2048,
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        blank=True, help_text="Headline / Key Point", max_length=500
                    ),
                ),
                (
                    "date_logged",
                    models.DateField(
                        default=django.utils.timezone.now, help_text="Date logged"
                    ),
                ),
                (
                    "week",
                    models.CharField(
                        blank=True,
                        help_text="Week label (e.g. 2025-W40)",
                        max_length=20,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("publisher_news", "Publisher News"),
                            ("general_market", "General Market Signal"),
                            ("compliance_update", "Compliance Update"),
                            (
                                "thought_leadership",
                                "Thought leadership / Trend article",
                            ),
                            ("market_forecast", "Market Trend / Industry Forecast"),
                            ("regulatory", "Regulatory update / analysis"),
                            ("potential_lead", "Potential Lead"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                (
                    "relevance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("potential_action", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("logged", "Logged"),
                            ("follow_up", "Follow up"),
                            ("done", "Done"),
                        ],
                        default="logged",
                        max_length=20,
                    ),
                ),
                (
                    "competitors",
                    models.TextField(
                        blank=True, help_text="Competitors or companies mentioned"
                    ),
                ),
                (
                    "competitors_notes",
                    models.TextField(
                        blank=True,
                        help_text="Primary audience, content focus, relevance to ICP, notes/positioning",
                    ),
                ),
                (
                    "linked_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signals",
                        to="crm.company",
                    ),
                ),
                (
                    "linked_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signals",
                        to="crm.contact",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Signals",
                "ordering": ["-date_logged", "-created_at"],
            },
        ),
    ]
