# Generated by Django 4.2 on 2026-01-31 06:40

import django.db.models.deletion
from django.db import migrations, models


def create_default_pipeline_and_backfill(apps, schema_editor):
    Pipeline = apps.get_model("crm", "Pipeline")
    PipelineStage = apps.get_model("crm", "PipelineStage")
    Deal = apps.get_model("crm", "Deal")
    stage_map = [
        ("prospecting", "Prospecting", 10),
        ("qualification", "Qualification", 25),
        ("proposal", "Proposal", 50),
        ("negotiation", "Negotiation", 75),
        ("closed_won", "Closed Won", 100),
        ("closed_lost", "Closed Lost", 0),
    ]
    pipeline, _ = Pipeline.objects.get_or_create(
        name="Sales",
        defaults={
            "description": "Default sales pipeline",
            "is_default": True,
            "is_active": True,
        },
    )
    # Ensure only one default
    Pipeline.objects.exclude(pk=pipeline.pk).update(is_default=False)
    stage_by_legacy = {}
    for order, (legacy_code, name, prob) in enumerate(stage_map):
        stage, _ = PipelineStage.objects.get_or_create(
            pipeline=pipeline,
            order=order,
            defaults={
                "name": name,
                "probability": prob,
                "is_closed": legacy_code in ("closed_won", "closed_lost"),
                "is_won": legacy_code == "closed_won",
            },
        )
        stage_by_legacy[legacy_code] = stage
    for deal in Deal.objects.all():
        deal.pipeline = pipeline
        deal.pipeline_stage = stage_by_legacy.get(deal.stage or "prospecting")
        deal.save(update_fields=["pipeline", "pipeline_stage"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0022_add_signal_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deals",
                to="crm.pipeline",
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="pipeline_stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deals",
                to="crm.pipelinestage",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("prospecting", "Prospecting"),
                    ("qualification", "Qualification"),
                    ("proposal", "Proposal"),
                    ("negotiation", "Negotiation"),
                    ("closed_won", "Closed Won"),
                    ("closed_lost", "Closed Lost"),
                ],
                default="prospecting",
                help_text="Legacy; use pipeline_stage when set.",
                max_length=20,
            ),
        ),
        migrations.RunPython(create_default_pipeline_and_backfill, noop_reverse),
    ]
