# Generated by Django 4.2 on 2026-01-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0025_add_team_and_user_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Label for this webhook", max_length=100
                    ),
                ),
                (
                    "url",
                    models.URLField(help_text="Endpoint URL to POST", max_length=2048),
                ),
                (
                    "secret",
                    models.CharField(
                        blank=True,
                        help_text="Secret for HMAC-SHA256 X-Webhook-Signature header",
                        max_length=255,
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        default=list,
                        help_text="List of event names, e.g. ['contact.create', 'contact.update']",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
