# Generated by Django 4.2 on 2026-02-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0026_add_webhook"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_signature",
            field=models.TextField(
                blank=True,
                help_text="HTML signature for outgoing emails (per-user; falls back to EMAIL_SIGNATURE_HTML if empty)",
            ),
        ),
    ]
