# Generated by Django 4.2 on 2026-03-03 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "0027_add_userprofile_email_signature"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.IntegerField(help_text="Plan year (e.g. 2026)")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional plan name (e.g. 2026 Newsletter Content)",
                        max_length=255,
                    ),
                ),
                (
                    "quarter_themes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Quarter themes, e.g. {"Q1": "Theme A", "Q2": "Theme B"}',
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter plan",
                "verbose_name_plural": "Newsletter plans",
                "ordering": ["-year"],
                "unique_together": {("year",)},
            },
        ),
        migrations.CreateModel(
            name="NewsletterEdition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quarter",
                    models.CharField(
                        choices=[
                            ("Q1", "Q1"),
                            ("Q2", "Q2"),
                            ("Q3", "Q3"),
                            ("Q4", "Q4"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "week_number",
                    models.PositiveIntegerField(help_text="Week number (1-52)"),
                ),
                (
                    "scheduled_date",
                    models.DateField(help_text="Start date for the week or day"),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        help_text="Day of week (optional, for daily rows)",
                        max_length=10,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        help_text="Weekly theme + daily topic",
                        max_length=500,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("drafting", "Drafting"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="drafting",
                        max_length=20,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Link to published newsletter"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newsletter_editions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editions",
                        to="crm.newsletterplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter edition",
                "verbose_name_plural": "Newsletter editions",
                "ordering": ["plan", "quarter", "scheduled_date", "week_number"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscribers_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Subscriber count at send time"
                    ),
                ),
                ("sent_count", models.PositiveIntegerField(default=0)),
                (
                    "opens_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Readers / unique opens"
                    ),
                ),
                ("clicks_count", models.PositiveIntegerField(default=0)),
                (
                    "ad_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Ad revenue from this edition",
                        max_digits=12,
                    ),
                ),
                ("unsubscribes_count", models.PositiveIntegerField(default=0)),
                ("bounces_count", models.PositiveIntegerField(default=0)),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last sync from ESP (Mailchimp, Beehiiv, etc.)",
                        null=True,
                    ),
                ),
                (
                    "edition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="crm.newsletteredition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter analytics",
                "verbose_name_plural": "Newsletter analytics",
            },
        ),
        migrations.CreateModel(
            name="NewsletterConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attribution_type",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("opportunity", "Opportunity"),
                            ("closed_won", "Closed Won"),
                        ],
                        default="lead",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletter_conversions",
                        to="crm.deal",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions",
                        to="crm.newsletteredition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter conversion",
                "verbose_name_plural": "Newsletter conversions",
                "ordering": ["-created_at"],
                "unique_together": {("edition", "deal")},
            },
        ),
    ]
