# Generated by Django 4.2 on 2026-03-04 09:30

from django.db import migrations, models


def copy_theme_to_weekly_theme(apps, schema_editor):
    NewsletterEdition = apps.get_model("crm", "NewsletterEdition")
    for edition in NewsletterEdition.objects.all():
        if hasattr(edition, "theme") and edition.theme:
            edition.weekly_theme = edition.theme
            edition.save(update_fields=["weekly_theme"])


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0028_add_newsletter_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletteredition",
            name="daily_topic",
            field=models.CharField(
                blank=True,
                help_text="Daily topic title (for day-level rows)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="newsletteredition",
            name="weekly_theme",
            field=models.CharField(
                blank=True, help_text="Weekly theme for this week", max_length=500
            ),
        ),
        migrations.RunPython(copy_theme_to_weekly_theme, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="newsletteredition",
            name="theme",
        ),
    ]
