# Generated by Django 4.2 on 2026-03-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0029_add_weekly_theme_daily_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsletteredition",
            name="day_of_week",
        ),
    ]
