# Generated by Django 4.2 on 2026-03-04 09:53

from django.db import migrations, models


def populate_day_of_week_from_scheduled_date(apps, schema_editor):
    NewsletterEdition = apps.get_model("crm", "NewsletterEdition")
    for edition in NewsletterEdition.objects.all():
        if hasattr(edition, "scheduled_date") and edition.scheduled_date:
            edition.day_of_week = edition.scheduled_date.strftime("%A")
            edition.save(update_fields=["day_of_week"])


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0030_remove_day_of_week_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletteredition",
            name="day_of_week",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                default="Monday",
                help_text="Day of week; date is derived from week_number + day_of_week",
                max_length=10,
            ),
        ),
        migrations.RunPython(populate_day_of_week_from_scheduled_date, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="newsletteredition",
            name="scheduled_date",
        ),
        migrations.AlterModelOptions(
            name="newsletteredition",
            options={
                "ordering": ["plan", "quarter", "week_number", "day_of_week"],
                "verbose_name": "Newsletter edition",
                "verbose_name_plural": "Newsletter editions",
            },
        ),
    ]
