# Generated by Django 4.2 on 2026-03-04 10:24

from datetime import timedelta

from django.db import migrations
from django.utils import timezone


def _scheduled_date_for_edition(edition):
    """Compute scheduled_date from plan year, week_number, day_of_week (same logic as model)."""
    year = edition.plan.year if edition.plan_id else timezone.now().year
    jan1 = timezone.datetime(year, 1, 1).date()
    days_until_monday = (7 - jan1.weekday()) % 7
    first_monday = jan1 + timedelta(days=days_until_monday)
    week_monday = first_monday + timedelta(days=(edition.week_number - 1) * 7)
    day_offset = {
        "Monday": 0,
        "Tuesday": 1,
        "Wednesday": 2,
        "Thursday": 3,
        "Friday": 4,
        "Saturday": 5,
        "Sunday": 6,
    }.get(edition.day_of_week or "Monday", 0)
    return week_monday + timedelta(days=day_offset)


def _quarter_from_date(d):
    if d is None:
        return "Q1"
    m = d.month
    if m <= 3:
        return "Q1"
    if m <= 6:
        return "Q2"
    if m <= 9:
        return "Q3"
    return "Q4"


def fix_edition_quarters(apps, schema_editor):
    NewsletterEdition = apps.get_model("crm", "NewsletterEdition")
    NewsletterPlan = apps.get_model("crm", "NewsletterPlan")
    for edition in NewsletterEdition.objects.select_related("plan"):
        if not edition.plan_id:
            continue
        try:
            sd = _scheduled_date_for_edition(edition)
            new_quarter = _quarter_from_date(sd)
            if edition.quarter != new_quarter:
                edition.quarter = new_quarter
                edition.save(update_fields=["quarter"])
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0031_derive_date_from_week_and_day"),
    ]

    operations = [
        migrations.RunPython(fix_edition_quarters, migrations.RunPython.noop),
    ]
