# Generated by Django 5.2.9 on 2026-03-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0032_auto_quarter_from_scheduled_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="newsletter_subscribed",
            field=models.BooleanField(
                default=False,
                help_text="Subscribed to the newsletter; gates sending of scheduled newsletter and welcome series.",
            ),
        ),
        migrations.AddField(
            model_name="newsletteredition",
            name="body_html",
            field=models.TextField(
                blank=True,
                help_text="HTML or plain text content of the newsletter to send",
            ),
        ),
        migrations.AddField(
            model_name="newsletteredition",
            name="sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this edition was sent to subscribers; null means not yet sent",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="newsletteredition",
            name="subject",
            field=models.CharField(
                blank=True,
                help_text="Email subject line for this edition",
                max_length=500,
            ),
        ),
    ]
