# Generated by Django 5.2.9 on 2026-03-15 07:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0033_add_newsletter_subscribed_and_edition_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="WelcomeEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Step order (1=first at signup, 2=+1h, 3=+4h, 4=+7h)",
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=500)),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Plain text or HTML body for this welcome email",
                    ),
                ),
                (
                    "offset_hours",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Hours after previous step to send (0 = at signup for step 1)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Welcome email step",
                "verbose_name_plural": "Welcome email steps",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WelcomeEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrolled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "current_step_index",
                    models.PositiveIntegerField(
                        default=0, help_text="Zero-based index of the next step to send"
                    ),
                ),
                (
                    "next_send_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to send the next welcome email",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welcome_enrollments",
                        to="crm.contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Welcome enrollment",
                "verbose_name_plural": "Welcome enrollments",
                "ordering": ["-enrolled_at"],
            },
        ),
    ]
