# Generated by Django 5.2.9 on 2026-03-15 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0035_seed_welcome_email_steps"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Template name for reuse", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter template",
                "verbose_name_plural": "Newsletter templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Issue title (and blog post title)", max_length=500
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL slug for the blog post (e.g. newsletter-2025-01-15)",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Email subject line (defaults to title if empty)",
                        max_length=500,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Optional meta title for blog (max 60 chars)",
                        max_length=60,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Optional meta description for blog (max 320 chars)",
                        max_length=320,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional scheduled date (for display/filtering)",
                        null=True,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When newsletter emails were sent",
                        null=True,
                    ),
                ),
                (
                    "blog_published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the post was published on www.kikodo.app",
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newsletter_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_from_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issues_created",
                        to="crm.newslettertemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter issue",
                "verbose_name_plural": "Newsletter issues",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterIssueSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("heading", models.CharField(max_length=500)),
                (
                    "body_markdown",
                    models.TextField(
                        blank=True, help_text="Markdown-formatted body for this section"
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="crm.newsletterissue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter issue section",
                "verbose_name_plural": "Newsletter issue sections",
                "ordering": ["issue", "order"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterTemplateSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("heading", models.CharField(max_length=500)),
                (
                    "body_markdown",
                    models.TextField(
                        blank=True, help_text="Markdown-formatted body for this section"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="crm.newslettertemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter template section",
                "verbose_name_plural": "Newsletter template sections",
                "ordering": ["template", "order"],
            },
        ),
    ]
