# Generated by Django 5.2.9 on 2026-03-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0036_add_newsletter_templates_and_issues"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletterissuesection",
            name="heading",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
