# Generated by Django 5.2.9 on 2026-03-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0037_allow_blank_issue_section_heading"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletterissue",
            name="divider_image_url",
            field=models.URLField(
                blank=True,
                help_text="Optional image URL to show between sections. If empty, a simple line divider is used.",
                max_length=500,
            ),
        ),
    ]
