# Generated by Django 5.2.9 on 2026-03-15 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0038_add_newsletter_issue_divider_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletterissue",
            name="edition",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to the plan edition this issue corresponds to (if created from plan).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="crm.newsletteredition",
            ),
        ),
    ]
