# Generated by Django 5.2.9 on 2026-03-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0039_add_newsletter_issue_edition_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsletteredition",
            name="daily_topic",
        ),
        migrations.AlterField(
            model_name="newsletteredition",
            name="weekly_theme",
            field=models.CharField(
                blank=True, help_text="Weekly topic for this week", max_length=500
            ),
        ),
    ]
