# Generated by Django 5.2.9 on 2026-03-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0040_remove_newsletter_edition_daily_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletterissue",
            name="preheader",
            field=models.CharField(
                blank=True,
                help_text="Optional email preheader/preview text shown by many inboxes (hidden in the HTML body).",
                max_length=255,
            ),
        ),
    ]
