# Generated by Django 4.2.7 on 2026-04-01 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0043_welcomeautomation_slug_blank"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="welcomeemail",
            options={
                "ordering": ["automation", "order"],
                "verbose_name": "Welcome email step",
                "verbose_name_plural": "Welcome email steps",
            },
        ),
    ]
