# Generated by Django 4.2.7 on 2026-09-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0044_alter_welcomeemail_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newslettertemplatesection",
            name="heading",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
