# Generated by Django 5.2.17 on 2026-09-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0045_alter_newslettertemplatesection_heading"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettertemplate",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="If set, new issues use this template without prompting.",
            ),
        ),
    ]
